resources:
  - name: mvn_repo
    type: GitRepo
    configuration:
      path: abhishekk012/jfrog-pipelines-maven-sample
      gitProvider: s_gitHub

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: ArtifactoryMain

pipelines:
  - name: demo_maven
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: prod-libs-snapshot
          deployerReleaseRepo: prod-libs-release
          inputResources:
            - name: mvn_repo
          integrations:
            - name: ArtifactoryMain

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
